name: PortalsPE
main: PortalsPE\Main
api: [2.0.0 , 3.0.0-ALPHA1 , 3.0.0-ALPHA2 , 3.0.0-ALPHA3 , 3.0.0-ALPHA4 , 3.0.0-ALPHA5 , 3.0.0-ALPHA6]
version: 1.0
author: luca28pet
description: A portals plugin
commands:
  portal:
    description: Main PortalsPE commmand
    usage: /portal pos1|pos2|create|list|delete <name>|fill <name> <fillid>
    permission: portal.admin
permission:
  portal.admin:
    description: admin command
    default: op
