name: PortalsPE
main: luca28pet\PortalsPE\Main
api: 4.0.0
version: 3.0.0
author: luca28pet
authors:
  - TheNote
description: A portals plugin
permissions:
  portalspe:
    default: false
  portalspe.portal:
    default: false
  portalspe.command:
    default: false
  portalspe.command.portal:
    default: op
